### ISSUE TITLE
NFS Root does not work

### ISSUE THREAD

**Issue by bzfbd** [mcusim/freebsd-src#7]
When trying to netboot over dpaa2 NFS Root mount hangs in kernel before init

**Comment by bzfbd** [comment]
Got a fix for that; will open a pull request the next days.

**Comment by dsalychev** [comment]
I haven't checked myself yet, but I assume root FS can be mounted from NFS on both HoneyComb and Ten64 starting from 452939456bf79e68bef92becbe7b145b43764a9f and 1f073757c03a89d7795df659f69c81d18281595a.
